name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:  
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY}} 
        REACT_APP_AUTHDOMAIN: ${{ secrets.REACT_APP_AUTHDOMAIN}} 
        REACT_APP_DATABASEURL: ${{ secrets.REACT_APP_DATABASEURL}} 
        REACT_APP_PROJECTID: ${{ secrets.REACT_APP_PROJECTID}} 
        REACT_APP_STORAGEBUCKET: ${{ secrets.REACT_APP_STORAGEBUCKET}} 
        REACT_APP_MESSAGINGSENDERID: ${{ secrets.REACT_APP_MESSAGINGSENDERID}} 
        REACT_APP_APPID: ${{ secrets.REACT_APP_APPID}} 
        REACT_APP_MEASUREMENTID: ${{ secrets.REACT_APP_MEASUREMENTID}}
